<?php

namespace App\Providers;

use App\Enums\Ability;
use App\Models\User;
use Dedoc\Scramble\Scramble;
use Dedoc\Scramble\Support\Generator\OpenApi;
use Dedoc\Scramble\Support\Generator\SecurityScheme;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\ServiceProvider;
use Illuminate\Validation\Rules\Password;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        $this->configureAuthorization();
        $this->configurePasswords();
        $this->configureRateLimiting();
        $this->configureApiDocs();
    }

    /**
     * One Gate per Ability. Use them anywhere Laravel authorizes:
     *   ->middleware('can:sales-orders.view')
     *   Gate::authorize(Ability::SalesOrdersView)
     *
     *   @can('users.manage') ... @endcan
     *
     * User::canUse() checks the user's roles AND, for API requests, the
     * abilities granted to the token in use. Admins pass every role check
     * but are still limited by their token's abilities.
     */
    private function configureAuthorization(): void
    {
        foreach (Ability::cases() as $ability) {
            Gate::define($ability->value, fn (User $user) => $user->canUse($ability));
        }
    }

    private function configurePasswords(): void
    {
        Password::defaults(function () {
            $rule = Password::min(12)->letters()->mixedCase()->numbers();

            return $this->app->isProduction() ? $rule->uncompromised() : $rule;
        });
    }

    private function configureRateLimiting(): void
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
        });
    }

    /**
     * OpenAPI docs at /docs/api, generated by Scramble from routes/api.php.
     *
     * Deliberately not an Ability: abilities can be granted to any role,
     * while the full endpoint list is for administrators only.
     */
    private function configureApiDocs(): void
    {
        Gate::define('viewApiDocs', fn (User $user) => $user->isAdmin());

        Scramble::configure()->withDocumentTransformers(function (OpenApi $openApi) {
            $openApi->secure(SecurityScheme::http('bearer'));
        });
    }
}
